common: &default_settings
  adapter: postgresql
  database: <%= ENV["DB_NAME"] || "backups_dashboard" %>
  host: <%= ENV["DB_HOST"] %>
  user: bluesquare
  port: <%= ENV["DB_PORT"] || 5432 %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 50

development:
  <<: *default_settings
  database: "backups_dashboard_heroku_staging"

test:
  <<: *default_settings
  database: "backups_dashboard_test"

production:
  <<: *default_settings
